services:

  web:
    image: antonio24073/wordpress:php7.4-apache
    container_name: wordpress_web
    restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: Hiezoa9bei9euC
      # WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        /* Extra Config */
        define('FS_METHOD', 'direct');
    volumes:
      - ./vol/wordpress/html:/var/www/html
    networks:
      - wordpress_network

  db:
    image: mysql:5.7
    container_name: wordpress_db
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: Hiezoa9bei9euC
      MYSQL_ROOT_PASSWORD: easypass
    volumes:
      - ./vol/mysql/data:/var/lib/mysql
    networks:
      - wordpress_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wordpress_phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: Hiezoa9bei9euC
    networks:
      - wordpress_network

networks:
  wordpress_network:
    driver: bridge