services:

  web:
    image: ${REPO}:php${PHP_VERSION}-${WEBSERVER}
    container_name: ${STACK_NAME}_web
    restart: always
    ports:
      - "${HOST_IP}:${WEB_PORT}:${WEB_PORT}"
      - "${HOST_IP}:${WEBS_PORT}:${WEBS_PORT}"
    environment:
      - DOMAIN=${DOMAIN}
      - WEB_PORT=${WEB_PORT}
      - WEBS_PORT=${WEBS_PORT}
      - CERT_COUNTRY=${CERT_COUNTRY}
      - CERT_STATE=${CERT_STATE}
      - CERT_CITY=${CERT_CITY}
      - CERT_ORG=${CERT_ORG}
      - CERT_ORG_UNIT=${CERT_ORG_UNIT}
      - TZ=${TZ}

      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_NAME=${DB_NAME}
      - WORDPRESS_DB_USER=${DB_USER}
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
      - WORDPRESS_TABLE_PREFIX=${DB_PREFIX}
      - WORDPRESS_DEBUG=${WORDPRESS_DEBUG}
      - WORDPRESS_CONFIG_EXTRA=require_once ABSPATH . 'config.extra.php';

      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_SECURE=${SMTP_SECURE}
      - SMTP_FROM=${SMTP_FROM}
      - SMTP_FROM_NAME=${SMTP_FROM_NAME}

    volumes:
      - ${STACK_SRC}:/var/www/html
      - ${STACK_VOLUME}/wordpress/certbot/www//:/var/www/certbot/:rw
      - ${STACK_VOLUME}/wordpress/certbot/conf/:/etc/letsencrypt/:rw
    networks:
      - wordpress_network
      - wp_cli_network
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY}
  certbot:
    image: certbot/certbot:latest
    container_name: ${STACK_NAME}_certbot
    networks:
      - wordpress_network
    depends_on:
      - web
    volumes:
      - ${STACK_VOLUME}/wordpress/certbot/www/.well-known/acme-challenge/:/var/www/html/.well-known/acme-challenge/:rw
      - ${STACK_VOLUME}/wordpress/certbot/conf/:/etc/letsencrypt/:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  db:
    image: mariadb:10.6
    container_name: ${STACK_NAME}_db
    restart: always
    # ports:
    #   - "${MARIADB_DB_PORT}:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - TZ=${TZ}
    volumes:
      - ${STACK_VOLUME}/mysql/data:/var/lib/mysql
    networks:
      - wordpress_network
      - wp_cli_network
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY}
  pma:
    image: phpmyadmin/phpmyadmin
    container_name: ${STACK_NAME}_pma
    restart: always
    ports:
      - "${PMA_PORT}:80"
    environment:
      - PMA_SSL_CERT=/etc/letsencrypt/live/${DOMAIN}/fullchain.pem
      - PMA_SSL_KEY=/etc/letsencrypt/live/${DOMAIN}/privkey.pem
      - PMA_HOST=db
      # - PMA_USER=${PMA_USER}
      # - PMA_PASSWORD=${PMA_PASSWORD}
      # - PMA_DATABASE=${PMA_DATABASE}
      # - MARIADB_ROOT_PASSWORD=${PMA_ROOT_PASSWORD}
    depends_on:
      - db
    networks:
      - wordpress_network
    volumes:
      - ${STACK_VOLUME}/wordpress/certbot/conf/:/etc/letsencrypt/:rw
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY}
networks:
  wordpress_network:
    name: ${STACK_NAME}_network
  wp_cli_network:
    external: true
    name: ${STACK_NAME}_cli_network
  